### PR TITLE
Update scarlet tutorial

### LINKED ISSUE #1: Edit scarlet tutorial for DESC+DC2
I'll push my edited scarlet tutorial ([original](https://github.com/LSSTScienceCollaborations/StackClub/blob/master/Deblending/scarlet_tutorial.ipynb)) that works in DESC env and with DC2 DR6 data to this repo. 

@herjy I'll let you know when it's here, and it would be great to have you review it!

### PR DESCRIPTION
**Pull request by yymao**
This PR is to resolve #1. 

@herjy I just realized that the notebook I've already edited is [lsst_stack_deblender.ipynb](https://github.com/LSSTScienceCollaborations/StackClub/blob/master/Deblending/lsst_stack_deblender.ipynb), not [scarlet_tutorial.ipynb](https://github.com/LSSTScienceCollaborations/StackClub/blob/master/Deblending/scarlet_tutorial.ipynb). The former is now in this PR.

Which one do you plan to use for your tutorial?

### CODE REVIEW

**Comment by herjy** [comment]
I was rather thinking of the tutorial, it is up to date with some of the convenience functions from scarlet.

**Comment by herjy** [comment]
But I'm actually fine with both. In any case there will be some editing from my part.

**Review by herjy — APPROVED** [review]
Nothing to say. Good job adapting it to DC2 images!

**Comment by yymao** [comment]
Thanks @herjy!

**Pull request merged**
